; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

[env]
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0

[seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
board_build.flash_mode = qio
upload_protocol = esptool
build_src_filter = 
	-<.git/>
	-<.svn/>
	+<*.h>
	+<${PIOENV}.cpp>


[lib_deps_softwareserial]
lib_deps = 
	plerup/EspSoftwareSerial@^8.2.0
	bolderflight/Bolder Flight Systems SBUS@^8.1.4

[env:toad_v01_sbus_receive]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_v02_drive_dynamixel_board]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v02_softwareserial]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v03_sbuscontrol]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v04_velocity_based]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v05_add_leds]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v06_failsafe_state]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v07_motor_deadband]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_moveServo_v08_update_to_arduino_core_3]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_servo2servo]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_simple_eyes_v01_blink]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_readParameters]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_serial_passthrough]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:toad_dynamixel_examples_generic_container]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:test_serial]
extends = seeed_xiao_esp32c3

[env:esp_dmxl_connTest_v01]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3

[env:crsf_receive_v01]
extends = lib_deps_softwareserial, seeed_xiao_esp32c3
